### ISSUE TITLE
use m as base unit

### ISSUE THREAD

**Issue by indus** [appalaszynski/length.js#10]
not **centi**meters but meters are the base unit of lenght measurement: https://en.wikipedia.org/wiki/SI_base_unit 
https://github.com/appalaszynski/length.js/blob/master/src/lib/units.js#L9

**Comment by Oxicode** [comment]
+1

**Comment by badulesia** [comment]
+1

**Comment by appalaszynski** [comment]
Addressed in e251037203014cadbca9c1f8fe42e9800c362c34.
