### ISSUE TITLE
suggestion : new units

### ISSUE THREAD

**Issue by badulesia** [appalaszynski/length.js#12]
Hello.
I have added decameter, hectometer, nautical mile and parsec to your code.
I have used the cm based system that you are using.
Nevertheless, I strongly recommand to use the meter as default unit. See remarks in issue #10 

	pm: Math.pow(10, -12),
	nm: Math.pow(10, -7),
	um: Math.pow(10, -4),
	mm: 0.1,
	cm: 1,
	dm: 10,
	m: Math.pow(10, 2),
	dam: Math.pow(10, 3),
	hm: Math.pow(10, 4),
	km: Math.pow(10, 5),
	in: 2.54,
	ft: 30.48,
	yd: 91.44,
	mi: 160934.4,
	nm: 185200,
	au: 14959787069100,
	ly: 946073047258080000,
	pc: 3085677581491367278,

**Comment by appalaszynski** [comment]
Addressed in e251037203014cadbca9c1f8fe42e9800c362c34.
