### ISSUE TITLE
I would like mm, um, and nm granularity

### ISSUE THREAD

**Issue by DoWhileGeek** [appalaszynski/length.js#3]
documented here, https://www.nist.gov/pml/weights-and-measures/prefixes

**Comment by renatoliveira** [comment]
@appalaszynski I believe this was addressed in https://github.com/appalaszynski/length.js/pull/7

**Comment by appalaszynski** [comment]
Adressed in eba5ddaf272dae0b62aba9acc8350e219afb5d40.
